# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a252ef89badb45683474c7ffed9e99ed215bdced5e77662c91a453cf571664724da13130ec2cf7020e67dde2b714f18f478acedeaf89e534a640574bbcad401

test:
  secret_key_base: b6dab49130190df55e3caf2d76f7a8b4529a14a632af7c6de618f75933a9bc6d0960a712e7fe3cf5924620309e267388e90bb759a493e413f125e74dfcb8cc85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
